set(debugcmake false)
if(debugcmake)
get_cmake_property(_variableNames VARIABLES)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
endif()

MESSAGE(STATUS "-------------------- Summary --------------------")
MESSAGE(STATUS "Fada cmake build type : '${CMAKE_BUILD_TYPE}'")
MESSAGE(STATUS "build shared libraries : '${BUILD_SHARED_LIBS}'")
MESSAGE(STATUS "CXX Compiler ID  : ${CMAKE_CXX_COMPILER_ID}")
MESSAGE(STATUS "CXX Compiler  : ${CMAKE_CXX_COMPILER}")
MESSAGE(STATUS "CXX Compiler flags : ${CMAKE_CXX_FLAGS}")
#get_directory_property( DirDefs DIRECTORY ${CMAKE_SOURCE_DIR} COMPILE_DEFINITIONS )
#foreach( d ${DirDefs} )
#    message( STATUS "CXX own FLags: " ${d} )
#endforeach()
MESSAGE(STATUS "Linker flags : ${CMAKE_EXE_LINKER_FLAGS}")
get_property(inc_dirs DIRECTORY PROPERTY INCLUDE_DIRECTORIES)
MESSAGE(STATUS "Include directories :  ${inc_dirs}")
MESSAGE(STATUS "Installation directory : ${CMAKE_INSTALL_PREFIX}")
MESSAGE(STATUS "Cmake module path : ${CMAKE_MODULE_PATH}")
MESSAGE(STATUS "CMAKE_SOURCE_DIR : ${CMAKE_SOURCE_DIR}")
MESSAGE(STATUS "CMAKE_INSTALL_PREFIX : ${CMAKE_INSTALL_PREFIX}")
MESSAGE(STATUS "Fada_EXTERNAL_LIBRARIES : ${Fada_EXTERNAL_LIBRARIES}")
MESSAGE(STATUS "-------------------------------------------------")
